orbs:
  maven: circleci/maven@1.3.0
version: 2.1
jobs:
  API-Automation:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          working_directory: ~/freenow-auto
          name: Test
          command:  mvn -s ./src/test/resources/APItestNG.xml clean test

workflows:
  sample: 
    jobs:
      - API-Automation

